influencers = [
    {"name": "Selena Gomez", "Instagram_follower_count": 430_000_000, "short_description": "Singer and actress", "country": "USA"},
    {"name": "Cristiano Ronaldo", "Instagram_follower_count": 600_000_000, "short_description": "Football player", "country": "Portugal"},
    {"name": "Kylie Jenner", "Instagram_follower_count": 400_000_000, "short_description": "Businesswoman and reality TV star", "country": "USA"},
    {"name": "Dwayne Johnson", "Instagram_follower_count": 360_000_000, "short_description": "Actor and former wrestler", "country": "USA"},
    {"name": "Kim Kardashian", "Instagram_follower_count": 340_000_000, "short_description": "Reality TV star and businesswoman", "country": "USA"},
    {"name": "Lionel Messi", "Instagram_follower_count": 455_000_000, "short_description": "Football player", "country": "Argentina"},
    {"name": "Ariana Grande", "Instagram_follower_count": 310_000_000, "short_description": "Singer and actress", "country": "USA"},
    {"name": "Beyoncé", "Instagram_follower_count": 290_000_000, "short_description": "Singer and actress", "country": "USA"},
    {"name": "Justin Bieber", "Instagram_follower_count": 280_000_000, "short_description": "Singer", "country": "Canada"},
    {"name": "Taylor Swift", "Instagram_follower_count": 250_000_000, "short_description": "Singer and songwriter", "country": "USA"},
    {"name": "Neymar Jr.", "Instagram_follower_count": 205_000_000, "short_description": "Football player", "country": "Brazil"},
    {"name": "Kendall Jenner", "Instagram_follower_count": 220_000_000, "short_description": "Model and TV personality", "country": "USA"},
    {"name": "Virat Kohli", "Instagram_follower_count": 255_000_000, "short_description": "Cricketer", "country": "India"},
    {"name": "Nicki Minaj", "Instagram_follower_count": 220_000_000, "short_description": "Rapper and singer", "country": "USA"},
    {"name": "Khloé Kardashian", "Instagram_follower_count": 220_000_000, "short_description": "Reality TV star", "country": "USA"},
    {"name": "Shawn Mendes", "Instagram_follower_count": 70_000_000, "short_description": "Singer and songwriter", "country": "Canada"},
    {"name": "Billie Eilish", "Instagram_follower_count": 110_000_000, "short_description": "Singer and songwriter", "country": "USA"},
    {"name": "LeBron James", "Instagram_follower_count": 140_000_000, "short_description": "Basketball player", "country": "USA"},
    {"name": "Gigi Hadid", "Instagram_follower_count": 80_000_000, "short_description": "Model", "country": "USA"},
    {"name": "Zayn Malik", "Instagram_follower_count": 50_000_000, "short_description": "Singer and former One Direction member", "country": "UK"},
    {"name": "Shakira", "Instagram_follower_count": 85_000_000, "short_description": "Singer", "country": "Colombia"},
    {"name": "Zendaya", "Instagram_follower_count": 180_000_000, "short_description": "Actress and singer", "country": "USA"},
    {"name": "Priyanka Chopra", "Instagram_follower_count": 90_000_000, "short_description": "Actress", "country": "India"},
    {"name": "Chris Hemsworth", "Instagram_follower_count": 100_000_000, "short_description": "Actor", "country": "Australia"},
    {"name": "Jennifer Lopez", "Instagram_follower_count": 250_000_000, "short_description": "Singer and actress", "country": "USA"},
    {"name": "Katy Perry", "Instagram_follower_count": 110_000_000, "short_description": "Singer and songwriter", "country": "USA"},
    {"name": "David Beckham", "Instagram_follower_count": 85_000_000, "short_description": "Former football player", "country": "UK"},
    {"name": "Gal Gadot", "Instagram_follower_count": 110_000_000, "short_description": "Actress", "country": "Israel"},
    {"name": "Dua Lipa", "Instagram_follower_count": 110_000_000, "short_description": "Singer and songwriter", "country": "UK"},
    {"name": "Emma Watson", "Instagram_follower_count": 70_000_000, "short_description": "Actress and activist", "country": "UK"},
    {"name": "Sophie Turner", "Instagram_follower_count": 15_000_000, "short_description": "Actress", "country": "UK"},
    {"name": "Kourtney Kardashian", "Instagram_follower_count": 220_000_000, "short_description": "Reality TV star", "country": "USA"},
    {"name": "Robert Downey Jr.", "Instagram_follower_count": 55_000_000, "short_description": "Actor", "country": "USA"},
    {"name": "Kevin Hart", "Instagram_follower_count": 150_000_000, "short_description": "Comedian and actor", "country": "USA"},
    {"name": "Camila Cabello", "Instagram_follower_count": 70_000_000, "short_description": "Singer and songwriter", "country": "Cuba"},
    {"name": "Sergio Ramos", "Instagram_follower_count": 75_000_000, "short_description": "Football player", "country": "Spain"},
    {"name": "Halsey", "Instagram_follower_count": 30_000_000, "short_description": "Singer", "country": "USA"},
    {"name": "Anitta", "Instagram_follower_count": 65_000_000, "short_description": "Singer", "country": "Brazil"},
    {"name": "Jason Momoa", "Instagram_follower_count": 20_000_000, "short_description": "Actor", "country": "USA"},
    {"name": "Gordon Ramsay", "Instagram_follower_count": 30_000_000, "short_description": "Celebrity chef", "country": "UK"},
    {"name": "Tom Holland", "Instagram_follower_count": 85_000_000, "short_description": "Actor", "country": "UK"},
    {"name": "Will Smith", "Instagram_follower_count": 65_000_000, "short_description": "Actor", "country": "USA"},
    {"name": "Mark Wahlberg", "Instagram_follower_count": 20_000_000, "short_description": "Actor and producer", "country": "USA"},
    {"name": "Bruno Mars", "Instagram_follower_count": 35_000_000, "short_description": "Singer", "country": "USA"},
    {"name": "Liam Payne", "Instagram_follower_count": 25_000_000, "short_description": "Singer and former One Direction member", "country": "UK"},
    {"name": "Miley Cyrus", "Instagram_follower_count": 200_000_000, "short_description": "Singer and actress", "country": "USA"},
    {"name": "Victoria Beckham", "Instagram_follower_count": 35_000_000, "short_description": "Fashion designer and former singer", "country": "UK"},
    {"name": "Conor McGregor", "Instagram_follower_count": 45_000_000, "short_description": "Mixed martial artist", "country": "Ireland"},
    {"name": "Khabib Nurmagomedov", "Instagram_follower_count": 40_000_000, "short_description": "Retired MMA fighter", "country": "Russia"},
    {"name": "Zlatan Ibrahimović", "Instagram_follower_count": 60_000_000, "short_description": "Football player", "country": "Sweden"}
]
